[workspace]

resolver = "2"

members = [
    "common",
    "dsntk",
    "evaluator",
    "examples",
    "feel",
    "feel-grammar",
    "feel-evaluator",
    "feel-number",
    "feel-parser",
    "feel-regex",
    "feel-temporal",
    "gendoc",
    "macros",
    "model",
    "model-evaluator",
    "recognizer",
    "server",
    "workspace"
]

[workspace.package]
version = "0.0.6"
authors = ["Dariusz Depta <depta@engos.de>"]
repository = "https://github.com/DecisionToolkit/dsntk-rs.git"
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.5.1"
base64 = "0.22.0"
chrono = "0.4.38"
chrono-tz = "0.9.0"
convert_case = "0.6.0"
clap = { version = "4.5.4", features = ["cargo"] }
dfp-number-sys = "0.1.0"
difference = "2.0.0"
domrs = "0.0.16"
markdown = "1.0.0-alpha.16"
once_cell = "1.19.0"
petgraph = "0.6.4"
proc-macro2 = "1.0.81"
quote = "1.0.36"
regex = "1.10.4"
reqwest = { version = "0.12.3", default-features = false, features = ["blocking", "json", "rustls-tls"] }
roxmltree = "0.19.0"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
syn = { version = "2.0.60", features = ["fold", "full"] }
uuid = { version = "1.8.0", features = ["v4"] }
uriparse = "0.6.4"
url = "2.5.0"
urlencoding = "2.1.3"
walkdir = "2.5.0"
dsntk-common = { path = "common" }
dsntk-evaluator = { path = "evaluator" }
dsntk-examples = { path = "examples" }
dsntk-feel = { path = "feel" }
dsntk-feel-evaluator = { path = "feel-evaluator" }
dsntk-feel-grammar = { path = "feel-grammar" }
dsntk-feel-number = { path = "feel-number" }
dsntk-feel-parser = { path = "feel-parser" }
dsntk-feel-regex = { path = "feel-regex" }
dsntk-feel-temporal = { path = "feel-temporal" }
dsntk-gendoc = { path = "gendoc" }
dsntk-macros = { path = "macros" }
dsntk-model = { path = "model" }
dsntk-model-evaluator = { path = "model-evaluator" }
dsntk-recognizer = { path = "recognizer" }
dsntk-server = { path = "server" }
dsntk-workspace = { path = "workspace" }
