[workspace]

resolver = "2"

members = [
    "common",
    "dsntk",
    "evaluator",
    "examples",
    "feel",
    "feel-grammar",
    "feel-evaluator",
    "feel-number",
    "feel-parser",
    "feel-temporal",
    "gendoc",
    "macros",
    "model",
    "model-evaluator",
    "recognizer",
    "server",
    "workspace"
]

[workspace.package]
version = "0.0.3"
authors = ["Dariusz Depta <dariusz.depta@dsntk.io>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.4.1"
base64 = "0.21.5"
chrono = "0.4.31"
chrono-tz = "0.8.4"
convert_case = "0.6.0"
clap = { version = "4.4.12", features = ["cargo"] }
dfp-number-sys = "0.0.19"
difference = "2.0.0"
domrs = "0.0.15"
markdown = "1.0.0-alpha.16"
once_cell = "1.19.0"
petgraph = "0.6.4"
quote = "1.0.33"
regex = "1.10.2"
reqwest = { version = "0.11.23", default-features = false, features = ["blocking", "json", "rustls-tls"] }
roxmltree = "0.19.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
syn = "2.0.43"
uuid = { version = "1.6.1", features = ["v4"] }
uriparse = "0.6.4"
url = "2.5.0"
urlencoding = "2.1.3"
walkdir = "2.4.0"
dsntk-common = { path = "common" }
dsntk-evaluator = { path = "evaluator" }
dsntk-examples = { path = "examples" }
dsntk-feel = { path = "feel" }
dsntk-feel-evaluator = { path = "feel-evaluator" }
dsntk-feel-grammar = { path = "feel-grammar" }
dsntk-feel-number = { path = "feel-number" }
dsntk-feel-parser = { path = "feel-parser" }
dsntk-feel-temporal = { path = "feel-temporal" }
dsntk-gendoc = { path = "gendoc" }
dsntk-macros = { path = "macros" }
dsntk-model = { path = "model" }
dsntk-model-evaluator = { path = "model-evaluator" }
dsntk-recognizer = { path = "recognizer" }
dsntk-server = { path = "server" }
dsntk-workspace = { path = "workspace" }
