[workspace]

resolver = "2"

members = [
    "common",
    "dsntk",
    "evaluator",
    "examples",
    "feel",
    "feel-grammar",
    "feel-evaluator",
    "feel-number",
    "feel-parser",
    "feel-temporal",
    "gendoc",
    "macros",
    "model",
    "model-evaluator",
    "recognizer",
    "server",
    "workspace"
]

[workspace.package]
version = "0.0.0"
authors = ["Dariusz Depta <dariusz.depta@dsntk.io>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.4.0"
base64 = "0.21.5"
chrono = "0.4.31"
chrono-tz = "0.8.4"
convert_case = "0.6.0"
clap = { version = "4.4.7", features = ["cargo"] }
dfp-number-sys = "0.0.14"
difference = "2.0.0"
domrs = "0.0.6"
markdown = "1.0.0-alpha.14"
once_cell = "1.18.0"
petgraph = "0.6.4"
quote = "1.0.33"
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false, features = ["blocking", "json", "rustls-tls"] }
roxmltree = "0.18.1"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
syn = "2.0.38"
uuid = { version = "1.5.0", features = ["v4"] }
uriparse = "0.6.4"
url = "2.4.1"
urlencoding = "2.1.3"
walkdir = "2.4.0"
dsntk-common = "0.0.0"
dsntk-evaluator = "0.0.0"
dsntk-examples = "0.0.0"
dsntk-feel = "0.0.0"
dsntk-feel-evaluator = "0.0.0"
dsntk-feel-grammar = "0.0.0"
dsntk-feel-number = "0.0.0"
dsntk-feel-parser = "0.0.0"
dsntk-feel-temporal = "0.0.0"
dsntk-gendoc = "0.0.0"
dsntk-macros = "0.0.0"
dsntk-model = "0.0.0"
dsntk-model-evaluator = "0.0.0"
dsntk-recognizer = "0.0.0"
dsntk-server = "0.0.0"
dsntk-workspace = "0.0.0"
